# Generated by Django 2.2.6 on 2023-05-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='substitle',
            new_name='subtitle',
        ),
    ]
